name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build Deps
      run: npm i && npm run build 

    - name: Firebase GitHub Action
      uses: pizzafox/firebase-action@1.0.7
      env:
        PROJECT_ID: "classtracker-624ff"
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy
